theme: jekyll-theme-dinky
title: Pokemon TGC Errors
description: Guide to rare misprint, error, and mistakes in the Pokemon TGC.
google_analytics:
show_downloads: false
github:
  is_project_page: false

