theme: jekyll-theme-dinky
title: Pokemon TCG Rares
description: Guide to rare misprint, error, and mistake cards in the Pokemon TCG.
repository: pokemontcgrares/pokemontcgrares.github.io
google_analytics: UA-11287535-3
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
